services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/morent?schema=public
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_DB=morent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - morent_db:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d morent"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  morent_db: